/* Dados de canvas transcritos dos previews em public/previews.
   Gerado a partir do HTML original; não é mock de UI.
   Cada camada tem id estável e nome curto para a árvore de camadas. */
import type { DocCanvas } from "./estudio-doc";

export const canvasBarretos: DocCanvas = {
  "kind": "canvas",
  "nome": "Barretos",
  "paginas": [
    {
      "id": "p1",
      "nome": "Tela 1",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -54.05,
          "y": -144.13,
          "w": 1188,
          "h": 1584,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/barretos/01-bg-stadium.jpg",
          "img": {
            "x": 0,
            "y": 0,
            "w": 1188,
            "h": 1584
          },
          "id": "p1-1",
          "nome": "bg stadium"
        },
        {
          "tipo": "imagem",
          "x": 65.67,
          "y": 271.83,
          "w": 334.16,
          "h": 334.16,
          "raio": 9999,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/barretos/02-circle-1955-photo.jpg",
          "img": {
            "x": -201.41,
            "y": -145.66,
            "w": 609.58,
            "h": 761
          },
          "id": "p1-2",
          "nome": "circle 1955 photo"
        },
        {
          "tipo": "forma",
          "x": 65.67,
          "y": 271.83,
          "w": 334.16,
          "h": 334.16,
          "raio": 9999,
          "borda": {
            "largura": 4,
            "cor": "#4ADC75"
          },
          "id": "p1-3",
          "nome": "anel"
        },
        {
          "tipo": "imagem",
          "x": 699.92,
          "y": 455.06,
          "w": 334.16,
          "h": 334.16,
          "raio": 9999,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/barretos/03-circle-festa-logo.jpg",
          "img": {
            "x": -294.23,
            "y": -282.23,
            "w": 937.21,
            "h": 1172.17
          },
          "id": "p1-4",
          "nome": "circle festa logo"
        },
        {
          "tipo": "forma",
          "x": 699.92,
          "y": 455.06,
          "w": 334.16,
          "h": 334.16,
          "raio": 9999,
          "borda": {
            "largura": 4,
            "cor": "#4ADC75"
          },
          "id": "p1-5",
          "nome": "anel"
        },
        {
          "tipo": "imagem",
          "x": -54.05,
          "y": -144.13,
          "w": 1188,
          "h": 1584,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/barretos/04-woman-cutout.png",
          "img": {
            "x": 0,
            "y": 0,
            "w": 1188,
            "h": 1584
          },
          "id": "p1-6",
          "nome": "woman cutout"
        },
        {
          "tipo": "imagem",
          "x": -497.77,
          "y": 580.65,
          "w": 2076,
          "h": 892,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/barretos/05-gradient-scrim.png",
          "img": {
            "x": 0,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p1-7",
          "nome": "gradient scrim"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p1-8",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "forma",
          "x": 108,
          "y": 989.89,
          "w": 249.36,
          "h": 58.97,
          "cor": "#4ADC75",
          "id": "p1-9",
          "nome": "retângulo"
        },
        {
          "tipo": "texto",
          "x": 125,
          "y": 1001.56,
          "fonte": "NYT Franklin",
          "peso": 600,
          "tamanho": 35.46,
          "entrelinha": 35.46,
          "entreLetras": 5.85,
          "cor": "#002820",
          "texto": "NEGÓCIOS",
          "id": "p1-10",
          "nome": "NEGÓCIOS"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1081.55,
          "w": 864,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 73.91,
          "entrelinha": 82,
          "cor": "#FFFFFF",
          "quebra": true,
          "partes": [
            {
              "texto": "Barretos",
              "peso": 700,
              "cor": "#4ADC75"
            },
            {
              "texto": ":",
              "peso": 700
            },
            {
              "texto": " como uma lona\nde circo virou um negócio\nde "
            },
            {
              "texto": "R$600 milhões",
              "peso": 700,
              "cor": "#4ADC75"
            },
            {
              "texto": "?"
            }
          ],
          "id": "p1-11",
          "nome": "Barretos: como uma lona de…"
        }
      ]
    }
  ]
};

export const canvasAgrum: DocCanvas = {
  "kind": "canvas",
  "nome": "Agrum Eleição",
  "paginas": [
    {
      "id": "p1",
      "nome": "Tela 1",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": -0.32,
          "w": 1080.64,
          "h": 1440.2,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img207.jpg",
          "img": {
            "x": -256.64,
            "y": -113.8,
            "w": 1696,
            "h": 1554
          },
          "id": "p1-1",
          "nome": "img207"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img210.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p1-2",
          "nome": "img210"
        },
        {
          "tipo": "forma",
          "x": 108,
          "y": 996.41,
          "w": 238.87,
          "h": 58.97,
          "cor": "#4ADC75",
          "id": "p1-3",
          "nome": "retângulo"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p1-4",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1084.14,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 88.58,
          "entrelinha": 111.85,
          "cor": "#FFFFFF",
          "texto": "O agro pode decidir ",
          "id": "p1-5",
          "nome": "O agro pode decidir"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1183.14,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 88.58,
          "entrelinha": 111.85,
          "cor": "#FFFFFF",
          "texto": "a ",
          "id": "p1-6",
          "nome": "a"
        },
        {
          "tipo": "texto",
          "x": 178.89,
          "y": 1183.14,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 88.58,
          "entrelinha": 111.85,
          "cor": "#4ADC75",
          "texto": "eleição de 2026",
          "id": "p1-7",
          "nome": "eleição de 2026"
        },
        {
          "tipo": "texto",
          "x": 792.23,
          "y": 1183.14,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 88.58,
          "entrelinha": 111.85,
          "cor": "#FFFFFF",
          "texto": "?",
          "id": "p1-8",
          "nome": "?"
        },
        {
          "tipo": "texto",
          "x": 131.03,
          "y": 1004.4,
          "fonte": "NYT Franklin",
          "peso": 600,
          "tamanho": 35.46,
          "entrelinha": 44.78,
          "cor": "#002820",
          "entreLetras": 5.85,
          "texto": "POLÍTICA",
          "id": "p1-9",
          "nome": "POLÍTICA"
        }
      ]
    },
    {
      "id": "p2",
      "nome": "Tela 2",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": -0.32,
          "w": 1080.64,
          "h": 1440.64,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img222.jpg",
          "img": {
            "x": -403.35,
            "y": -82.23,
            "w": 1813,
            "h": 1523
          },
          "id": "p2-1",
          "nome": "img222"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img225.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p2-2",
          "nome": "img225"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img225.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p2-3",
          "nome": "img225"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img225.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p2-4",
          "nome": "img225"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p2-5",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 871.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "Em 2022, Lula venceu Jair Bolsonaro ",
          "id": "p2-6",
          "nome": "Em 2022, Lula venceu Jair …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 925.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "por pouco mais de ",
          "id": "p2-7",
          "nome": "por pouco mais de"
        },
        {
          "tipo": "texto",
          "x": 507.23,
          "y": 925.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.02,
          "texto": "2.1 milhões de votos",
          "id": "p2-8",
          "nome": "2.1 milhões de votos"
        },
        {
          "tipo": "texto",
          "x": 955.8,
          "y": 925.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p2-9",
          "nome": "."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 979.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.11,
          "texto": "Foram 60.3 milhões contra 58.2 milhões.",
          "id": "p2-10",
          "nome": "Foram 60.3 milhões contra …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1087.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "Em um país com mais de 118 milhões de",
          "id": "p2-11",
          "nome": "Em um país com mais de 118…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1141.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "votos válidos, a diferença terminou em",
          "id": "p2-12",
          "nome": "votos válidos, a diferença…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1195.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "texto": "apenas 1.8 ponto percentual",
          "id": "p2-13",
          "nome": "apenas 1.8 ponto percentua…"
        },
        {
          "tipo": "texto",
          "x": 726.11,
          "y": 1195.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p2-14",
          "nome": "."
        }
      ]
    },
    {
      "id": "p3",
      "nome": "Tela 3",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": -0.32,
          "w": 1080.64,
          "h": 1440.27,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img239.jpg",
          "img": {
            "x": -467.5,
            "y": -290.73,
            "w": 2311,
            "h": 1731
          },
          "id": "p3-1",
          "nome": "img239"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img242.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p3-2",
          "nome": "img242"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img242.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p3-3",
          "nome": "img242"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img242.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p3-4",
          "nome": "img242"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p3-5",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 871.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.03,
          "texto": "No segundo turno, Bolsonaro venceu em",
          "id": "p3-6",
          "nome": "No segundo turno, Bolsonar…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 925.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "alguns dos principais estados produtores:",
          "id": "p3-7",
          "nome": "alguns dos principais esta…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1033.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.2,
          "texto": "Mato Grosso",
          "id": "p3-8",
          "nome": "Mato Grosso"
        },
        {
          "tipo": "texto",
          "x": 380.92,
          "y": 1033.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ": 65,1%",
          "id": "p3-9",
          "nome": ": 65,1%"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1087.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.36,
          "texto": "Paraná",
          "id": "p3-10",
          "nome": "Paraná"
        },
        {
          "tipo": "texto",
          "x": 258.16,
          "y": 1087.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ": 62,4%",
          "id": "p3-11",
          "nome": ": 62,4%"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1141.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.12,
          "texto": "Mato Grosso do Sul",
          "id": "p3-12",
          "nome": "Mato Grosso do Sul"
        },
        {
          "tipo": "texto",
          "x": 531.22,
          "y": 1141.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ": 59,5%",
          "id": "p3-13",
          "nome": ": 59,5%"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1195.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "texto": "Goiás",
          "id": "p3-14",
          "nome": "Goiás"
        },
        {
          "tipo": "texto",
          "x": 227.77,
          "y": 1195.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ": 58,7%",
          "id": "p3-15",
          "nome": ": 58,7%"
        }
      ]
    },
    {
      "id": "p4",
      "nome": "Tela 4",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": -0.32,
          "w": 1080.64,
          "h": 1440.64,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img256.jpg",
          "img": {
            "x": -214.74,
            "y": -76.59,
            "w": 1490,
            "h": 1550
          },
          "id": "p4-1",
          "nome": "img256"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img259.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p4-2",
          "nome": "img259"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img259.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p4-3",
          "nome": "img259"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img259.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p4-4",
          "nome": "img259"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img259.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p4-5",
          "nome": "img259"
        },
        {
          "tipo": "texto",
          "x": 494.23,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p4-6",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 781.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": 0.02,
          "texto": "Há uma coincidência importante entre",
          "id": "p4-7",
          "nome": "Há uma coincidência import…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 835.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": 0.02,
          "texto": "esse mapa eleitoral e uma parte",
          "id": "p4-8",
          "nome": "esse mapa eleitoral e uma …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 889.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "relevante do mapa econômico do agro.",
          "id": "p4-9",
          "nome": "relevante do mapa econômic…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 997.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.07,
          "texto": "Mato Grosso lidera a produção nacional",
          "id": "p4-10",
          "nome": "Mato Grosso lidera a produ…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1051.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "de ",
          "id": "p4-11",
          "nome": "de"
        },
        {
          "tipo": "texto",
          "x": 173.28,
          "y": 1051.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.09,
          "texto": "grãos",
          "id": "p4-12",
          "nome": "grãos"
        },
        {
          "tipo": "texto",
          "x": 293.73,
          "y": 1051.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.09,
          "texto": ". Paraná é uma potência em",
          "id": "p4-13",
          "nome": ". Paraná é uma potência em"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1105.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.05,
          "texto": "grãos e ",
          "id": "p4-14",
          "nome": "grãos e"
        },
        {
          "tipo": "texto",
          "x": 274.31,
          "y": 1105.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.02,
          "texto": "proteína animal",
          "id": "p4-15",
          "nome": "proteína animal"
        },
        {
          "tipo": "texto",
          "x": 612.34,
          "y": 1105.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.16,
          "texto": ". Goiás e Mato",
          "id": "p4-16",
          "nome": ". Goiás e Mato"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1159.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "Grosso do Sul também ocupam posições",
          "id": "p4-17",
          "nome": "Grosso do Sul também ocupa…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1213.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.04,
          "texto": "centrais na ",
          "id": "p4-18",
          "nome": "centrais na"
        },
        {
          "tipo": "texto",
          "x": 351.14,
          "y": 1213.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.04,
          "texto": "agricultura",
          "id": "p4-19",
          "nome": "agricultura"
        },
        {
          "tipo": "texto",
          "x": 587.5,
          "y": 1213.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": " e na ",
          "id": "p4-20",
          "nome": "e na"
        },
        {
          "tipo": "texto",
          "x": 706.19,
          "y": 1213.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "texto": "pecuária",
          "id": "p4-21",
          "nome": "pecuária"
        },
        {
          "tipo": "texto",
          "x": 891.5,
          "y": 1213.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p4-22",
          "nome": "."
        }
      ]
    },
    {
      "id": "p5",
      "nome": "Tela 5",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "forma",
          "x": 108,
          "y": 274.89,
          "w": 864.31,
          "h": 601.26,
          "cor": "#FFFFFF",
          "id": "p5-1",
          "nome": "retângulo"
        },
        {
          "tipo": "imagem",
          "x": 206.39,
          "y": 301.56,
          "w": 667,
          "h": 548,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img62.jpg",
          "img": {
            "x": 0,
            "y": -2.61,
            "w": 667,
            "h": 553
          },
          "id": "p5-2",
          "nome": "img62"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p5-3",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 893.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.04,
          "texto": "Essa proximidade política também",
          "id": "p5-4",
          "nome": "Essa proximidade política …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 947.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "apareceu fora das urnas.",
          "id": "p5-5",
          "nome": "apareceu fora das urnas."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1055.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": 0.02,
          "texto": "Segundo levantamento da ",
          "id": "p5-6",
          "nome": "Segundo levantamento da"
        },
        {
          "tipo": "texto",
          "x": 665.45,
          "y": 1055.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.8,
          "texto": "Folha",
          "id": "p5-7",
          "nome": "Folha"
        },
        {
          "tipo": "texto",
          "x": 780.14,
          "y": 1055.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ", feito a",
          "id": "p5-8",
          "nome": ", feito a"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1109.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.09,
          "texto": "partir de dados do TSE e da Receita",
          "id": "p5-9",
          "nome": "partir de dados do TSE e d…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1163.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.1,
          "texto": "Federal, sócios de empresas ligadas ao",
          "id": "p5-10",
          "nome": "Federal, sócios de empresa…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1217.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "agronegócio doaram ",
          "id": "p5-11",
          "nome": "agronegócio doaram"
        },
        {
          "tipo": "texto",
          "x": 546.89,
          "y": 1217.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "texto": "R$15.3 milhões",
          "id": "p5-12",
          "nome": "R$15.3 milhões"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1271.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.02,
          "texto": "para campanhas em 2022",
          "id": "p5-13",
          "nome": "para campanhas em 2022"
        },
        {
          "tipo": "texto",
          "x": 668.17,
          "y": 1271.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p5-14",
          "nome": "."
        }
      ]
    },
    {
      "id": "p6",
      "nome": "Tela 6",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 0,
          "w": 1080.64,
          "h": 1440,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img284.jpg",
          "img": {
            "x": -740.7,
            "y": 0,
            "w": 2176,
            "h": 1440
          },
          "id": "p6-1",
          "nome": "img284"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img287.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p6-2",
          "nome": "img287"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img287.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p6-3",
          "nome": "img287"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img287.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p6-4",
          "nome": "img287"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img287.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p6-5",
          "nome": "img287"
        },
        {
          "tipo": "texto",
          "x": 494.23,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p6-6",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 767.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "Ainda segundo o levantamento, ",
          "id": "p6-7",
          "nome": "Ainda segundo o levantamen…"
        },
        {
          "tipo": "texto",
          "x": 738.78,
          "y": 767.4,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#4ADC75",
          "entreLetras": -0.03,
          "texto": "candidatos",
          "id": "p6-8",
          "nome": "candidatos"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 818.4,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#4ADC75",
          "entreLetras": -0.02,
          "texto": "do PL receberam 21 vezes mais recursos",
          "id": "p6-9",
          "nome": "do PL receberam 21 vezes m…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 869.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "desses empresários do que candidatos do",
          "id": "p6-10",
          "nome": "desses empresários do que …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 920.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.21,
          "texto": "PT. Bolsonaro recebeu sozinho ",
          "id": "p6-11",
          "nome": "PT. Bolsonaro recebeu sozi…"
        },
        {
          "tipo": "texto",
          "x": 722.5,
          "y": 920.4,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#4ADC75",
          "texto": "R$ 3.2",
          "id": "p6-12",
          "nome": "R$ 3.2"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 971.4,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#4ADC75",
          "texto": "milhões",
          "id": "p6-13",
          "nome": "milhões"
        },
        {
          "tipo": "texto",
          "x": 267.19,
          "y": 971.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "texto": " e foi o candidato mais beneficiado",
          "id": "p6-14",
          "nome": "e foi o candidato mais ben…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1022.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.03,
          "texto": "pelas doações desse grupo.",
          "id": "p6-15",
          "nome": "pelas doações desse grupo."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1124.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "texto": "O dado indica uma ",
          "id": "p6-16",
          "nome": "O dado indica uma"
        },
        {
          "tipo": "texto",
          "x": 489.72,
          "y": 1124.4,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#4ADC75",
          "entreLetras": -0.04,
          "texto": "preferência clara",
          "id": "p6-17",
          "nome": "preferência clara"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1175.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "dentro de uma parcela empresarial do setor",
          "id": "p6-18",
          "nome": "dentro de uma parcela empr…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1226.4,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 46.17,
          "entrelinha": 58.3,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "naquele ciclo eleitoral.",
          "id": "p6-19",
          "nome": "naquele ciclo eleitoral."
        }
      ]
    },
    {
      "id": "p7",
      "nome": "Tela 7",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": -0.32,
          "w": 1080.64,
          "h": 1440.2,
          "opacidade": 0.9,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img303.jpg",
          "img": {
            "x": -263.67,
            "y": -113.8,
            "w": 2335,
            "h": 1554
          },
          "id": "p7-1",
          "nome": "img303"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img306.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p7-2",
          "nome": "img306"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img306.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p7-3",
          "nome": "img306"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img306.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p7-4",
          "nome": "img306"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img306.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p7-5",
          "nome": "img306"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 603.3,
          "w": 1080.64,
          "h": 837.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img306.png",
          "img": {
            "x": -481.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p7-6",
          "nome": "img306"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p7-7",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 758.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "Mas isso ainda não permite falar em um",
          "id": "p7-8",
          "nome": "Mas isso ainda não permite…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 812.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.74,
          "texto": "único “",
          "id": "p7-9",
          "nome": "único “"
        },
        {
          "tipo": "texto",
          "x": 249,
          "y": 812.06,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#4ADC75",
          "entreLetras": -0.03,
          "texto": "voto do agro",
          "id": "p7-10",
          "nome": "voto do agro"
        },
        {
          "tipo": "texto",
          "x": 520.95,
          "y": 812.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.5,
          "texto": "”. Um produtor de",
          "id": "p7-11",
          "nome": "”. Um produtor de"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 866.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "soja em Sorriso, um funcionário de",
          "id": "p7-12",
          "nome": "soja em Sorriso, um funcio…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 920.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.04,
          "texto": "frigorífico em Goiás e um executivo de",
          "id": "p7-13",
          "nome": "frigorífico em Goiás e um …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 974.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.07,
          "texto": "uma trading em São Paulo podem fazer",
          "id": "p7-14",
          "nome": "uma trading em São Paulo p…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1028.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": 0.04,
          "texto": "parte da mesma cadeia.",
          "id": "p7-15",
          "nome": "parte da mesma cadeia."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1136.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "texto": "Isso não significa que votem pelas",
          "id": "p7-16",
          "nome": "Isso não significa que vot…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1190.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "mesmas razões ou tenham as mesmas",
          "id": "p7-17",
          "nome": "mesmas razões ou tenham as…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1244.06,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 48.84,
          "entrelinha": 61.67,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "preferências políticas.",
          "id": "p7-18",
          "nome": "preferências políticas."
        }
      ]
    },
    {
      "id": "p8",
      "nome": "Tela 8",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": 0,
          "y": 0,
          "w": 1079.65,
          "h": 1439.86,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img86.png",
          "img": {
            "x": -993.53,
            "y": -403.14,
            "w": 2765,
            "h": 1843
          },
          "id": "p8-1",
          "nome": "img86"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img324.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p8-2",
          "nome": "img324"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img324.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p8-3",
          "nome": "img324"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img324.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p8-4",
          "nome": "img324"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img324.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p8-5",
          "nome": "img324"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 603.3,
          "w": 1080.64,
          "h": 837.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img324.png",
          "img": {
            "x": -481.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p8-6",
          "nome": "img324"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#002820",
          "texto": "AGRUM JORNAL",
          "id": "p8-7",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 758.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "Nessas eleições, um candidato ",
          "id": "p8-8",
          "nome": "Nessas eleições, um candid…"
        },
        {
          "tipo": "texto",
          "x": 747.91,
          "y": 758.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "não",
          "id": "p8-9",
          "nome": "não"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 811.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.03,
          "texto": "precisa vencer um grande estado",
          "id": "p8-10",
          "nome": "precisa vencer um grande e…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 864.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.03,
          "texto": "produtor para alterar o resultado nacional.",
          "id": "p8-11",
          "nome": "produtor para alterar o re…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 970.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.01,
          "texto": "Se uma diferença estadual cai de 30 para",
          "id": "p8-12",
          "nome": "Se uma diferença estadual …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1023.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": 0.08,
          "texto": "20 pontos, parte importante da vantagem",
          "id": "p8-13",
          "nome": "20 pontos, parte important…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1076.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "acumulada pelo adversário desaparece.",
          "id": "p8-14",
          "nome": "acumulada pelo adversário …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1182.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": 0.06,
          "texto": "Em eleições apertadas, ",
          "id": "p8-15",
          "nome": "Em eleições apertadas,"
        },
        {
          "tipo": "texto",
          "x": 593.86,
          "y": 1182.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.02,
          "texto": "reduzir derrotas",
          "id": "p8-16",
          "nome": "reduzir derrotas"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1235.01,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": 0.07,
          "texto": "também é importante",
          "id": "p8-17",
          "nome": "também é importante"
        },
        {
          "tipo": "texto",
          "x": 565.64,
          "y": 1235.01,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p8-18",
          "nome": "."
        }
      ]
    },
    {
      "id": "p9",
      "nome": "Tela 9",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p9-1",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 789.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "E 2026 voltou a apresentar uma disputa",
          "id": "p9-2",
          "nome": "E 2026 voltou a apresentar…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 842.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "bastante próxima. Segundo pesquisa",
          "id": "p9-3",
          "nome": "bastante próxima. Segundo …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 895.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.15,
          "texto": "PoderData/Aya, realizada entre 23 e 26",
          "id": "p9-4",
          "nome": "PoderData/Aya, realizada e…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 948.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.14,
          "texto": "de agosto, ",
          "id": "p9-5",
          "nome": "de agosto,"
        },
        {
          "tipo": "texto",
          "x": 331.59,
          "y": 948.57,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "Lula aparece com 45% e",
          "id": "p9-6",
          "nome": "Lula aparece com 45% e"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1001.57,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "Flávio Bolsonaro com 44% em um",
          "id": "p9-7",
          "nome": "Flávio Bolsonaro com 44% e…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1054.57,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": 0.03,
          "texto": "eventual segundo turno",
          "id": "p9-8",
          "nome": "eventual segundo turno"
        },
        {
          "tipo": "texto",
          "x": 605.92,
          "y": 1054.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p9-9",
          "nome": "."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1160.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.04,
          "texto": "A diferença está dentro da margem de",
          "id": "p9-10",
          "nome": "A diferença está dentro da…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1213.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "erro de ",
          "id": "p9-11",
          "nome": "erro de"
        },
        {
          "tipo": "texto",
          "x": 265.91,
          "y": 1213.57,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "dois pontos percentuais",
          "id": "p9-12",
          "nome": "dois pontos percentuais"
        },
        {
          "tipo": "texto",
          "x": 769.03,
          "y": 1213.57,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p9-13",
          "nome": "."
        }
      ]
    },
    {
      "id": "p10",
      "nome": "Tela 10",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": 0,
          "y": 0,
          "w": 1080,
          "h": 1440,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img101.jpg",
          "img": {
            "x": -724.6,
            "y": 0,
            "w": 2880,
            "h": 1440
          },
          "id": "p10-1",
          "nome": "img101"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img349.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p10-2",
          "nome": "img349"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img349.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p10-3",
          "nome": "img349"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 580.65,
          "w": 1080.64,
          "h": 859.67,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img349.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p10-4",
          "nome": "img349"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 587.3,
          "w": 1080.64,
          "h": 853.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img349.png",
          "img": {
            "x": -497.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p10-5",
          "nome": "img349"
        },
        {
          "tipo": "imagem",
          "x": -0.32,
          "y": 603.3,
          "w": 1080.64,
          "h": 837.02,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img349.png",
          "img": {
            "x": -481.45,
            "y": 0,
            "w": 2076,
            "h": 892
          },
          "espelhoY": true,
          "id": "p10-6",
          "nome": "img349"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p10-7",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 742.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": 0.02,
          "texto": "É por isso que temas específicos do agro",
          "id": "p10-8",
          "nome": "É por isso que temas espec…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 795.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "entram com força na disputa eleitoral.",
          "id": "p10-9",
          "nome": "entram com força na disput…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 901.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.05,
          "texto": "Crédito rural, juros, infraestrutura,",
          "id": "p10-10",
          "nome": "Crédito rural, juros, infr…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 954.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.1,
          "texto": "fertilizantes, comércio exterior, seguro,",
          "id": "p10-11",
          "nome": "fertilizantes, comércio ex…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1007.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "tributação, meio ambiente e segurança",
          "id": "p10-12",
          "nome": "tributação, meio ambiente …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1060.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "jurídica ",
          "id": "p10-13",
          "nome": "jurídica"
        },
        {
          "tipo": "texto",
          "x": 266.7,
          "y": 1060.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.04,
          "texto": "afetam diretamente a renda",
          "id": "p10-14",
          "nome": "afetam diretamente a renda"
        },
        {
          "tipo": "texto",
          "x": 853.94,
          "y": 1060.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": " e o",
          "id": "p10-15",
          "nome": "e o"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.12,
          "texto": "investimento em regiões ligadas ao setor.",
          "id": "p10-16",
          "nome": "investimento em regiões li…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1219.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "São decisões econômicas com",
          "id": "p10-17",
          "nome": "São decisões econômicas co…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1272.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "consequência eleitoral.",
          "id": "p10-18",
          "nome": "consequência eleitoral."
        }
      ]
    },
    {
      "id": "p11",
      "nome": "Tela 11",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": 108,
          "y": 266.86,
          "w": 864,
          "h": 439,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img111.jpg",
          "img": {
            "x": 0,
            "y": -17.17,
            "w": 864,
            "h": 516
          },
          "id": "p11-1",
          "nome": "img111"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p11-2",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 742.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.04,
          "texto": "Então, o agro pode decidir 2026?",
          "id": "p11-3",
          "nome": "Então, o agro pode decidir…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 848.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -1.28,
          "texto": "Pode ter peso decisivo se a diferença",
          "id": "p11-4",
          "nome": "Pode ter peso decisivo se …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 901.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "nacional continuar pequena. ",
          "id": "p11-5",
          "nome": "nacional continuar pequena…"
        },
        {
          "tipo": "texto",
          "x": 695.73,
          "y": 901.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "Os dados",
          "id": "p11-6",
          "nome": "Os dados"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 954.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.2,
          "texto": "não mostram um único “voto do agro”",
          "id": "p11-7",
          "nome": "não mostram um único “voto…"
        },
        {
          "tipo": "texto",
          "x": 907.16,
          "y": 954.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p11-8",
          "nome": "."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1060.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": 0.02,
          "texto": "Mostram, porém, que parte importante da",
          "id": "p11-9",
          "nome": "Mostram, porém, que parte …"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.19,
          "texto": "atividade agropecuária ",
          "id": "p11-10",
          "nome": "atividade agropecuária"
        },
        {
          "tipo": "texto",
          "x": 577.52,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.07,
          "texto": "está concentrada",
          "id": "p11-11",
          "nome": "está concentrada"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1166.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "em territórios onde as diferenças",
          "id": "p11-12",
          "nome": "em territórios onde as dif…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1219.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.05,
          "texto": "eleitorais foram expressivas em 2022",
          "id": "p11-13",
          "nome": "eleitorais foram expressiv…"
        },
        {
          "tipo": "texto",
          "x": 899.22,
          "y": 1219.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p11-14",
          "nome": "."
        }
      ]
    },
    {
      "id": "p12",
      "nome": "Tela 12",
      "largura": 1080,
      "altura": 1440,
      "fundo": "#002820",
      "camadas": [
        {
          "tipo": "imagem",
          "x": 108,
          "y": 253.58,
          "w": 864,
          "h": 466,
          "src": "https://sites-blank-editor-supabase.ickanz.easypanel.host/storage/v1/object/public/templates/agrum-eleicao/img116.png",
          "img": {
            "x": 0,
            "y": 0,
            "w": 864,
            "h": 576
          },
          "id": "p12-1",
          "nome": "img116"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 111.91,
          "fonte": "Anicon Sans",
          "peso": 400,
          "tamanho": 99.99,
          "entrelinha": 111.49,
          "cor": "#FFFFFF",
          "texto": "AGRUM JORNAL",
          "id": "p12-2",
          "nome": "AGRUM JORNAL"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 742.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "Em uma eleição decidida nas ",
          "id": "p12-3",
          "nome": "Em uma eleição decidida na…"
        },
        {
          "tipo": "texto",
          "x": 713.5,
          "y": 742.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "margens",
          "id": "p12-4",
          "nome": "margens"
        },
        {
          "tipo": "texto",
          "x": 896.55,
          "y": 742.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ",",
          "id": "p12-5",
          "nome": ","
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 795.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "mudanças nesses saldos podem afetar o",
          "id": "p12-6",
          "nome": "mudanças nesses saldos pod…"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 848.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "resultado nacional",
          "id": "p12-7",
          "nome": "resultado nacional"
        },
        {
          "tipo": "texto",
          "x": 494.2,
          "y": 848.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p12-8",
          "nome": "."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 954.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.02,
          "texto": "Se você é do agro, comente ",
          "id": "p12-9",
          "nome": "Se você é do agro, comente"
        },
        {
          "tipo": "texto",
          "x": 689.88,
          "y": 954.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "em quem",
          "id": "p12-10",
          "nome": "em quem"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1007.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.04,
          "texto": "pretende votar e porquê",
          "id": "p12-11",
          "nome": "pretende votar e porquê"
        },
        {
          "tipo": "texto",
          "x": 617.56,
          "y": 1007.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p12-12",
          "nome": "."
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": "O jornal ",
          "id": "p12-13",
          "nome": "O jornal"
        },
        {
          "tipo": "texto",
          "x": 277.88,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "texto": "Agrum",
          "id": "p12-14",
          "nome": "Agrum"
        },
        {
          "tipo": "texto",
          "x": 418.78,
          "y": 1113.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": " é o espaço de quem",
          "id": "p12-15",
          "nome": "é o espaço de quem"
        },
        {
          "tipo": "texto",
          "x": 108,
          "y": 1166.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "entreLetras": -0.07,
          "texto": "constrói o Brasil. ",
          "id": "p12-16",
          "nome": "constrói o Brasil."
        },
        {
          "tipo": "texto",
          "x": 459.13,
          "y": 1166.13,
          "fonte": "NYT Franklin",
          "peso": 700,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#4ADC75",
          "entreLetras": -0.03,
          "texto": "Siga-nos para mais",
          "id": "p12-17",
          "nome": "Siga-nos para mais"
        },
        {
          "tipo": "texto",
          "x": 861.7,
          "y": 1166.13,
          "fonte": "NYT Franklin",
          "peso": 300,
          "tamanho": 47.5,
          "entrelinha": 59.98,
          "cor": "#FFFFFF",
          "texto": ".",
          "id": "p12-18",
          "nome": "."
        }
      ]
    }
  ]
};
