/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DDesignIdRouteImport } from './routes/d.$designId'
import { Route as DDesignIdIndexRouteImport } from './routes/d.$designId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DDesignIdRoute = DDesignIdRouteImport.update({
  id: '/d/$designId',
  path: '/d/$designId',
  getParentRoute: () => rootRouteImport,
} as any)
const DDesignIdIndexRoute = DDesignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DDesignIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/d/$designId': typeof DDesignIdRouteWithChildren
  '/d/$designId/': typeof DDesignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/d/$designId': typeof DDesignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/d/$designId': typeof DDesignIdRouteWithChildren
  '/d/$designId/': typeof DDesignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/d/$designId' | '/d/$designId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/d/$designId'
  id: '__root__' | '/' | '/d/$designId' | '/d/$designId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DDesignIdRoute: typeof DDesignIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$designId': {
      id: '/d/$designId'
      path: '/d/$designId'
      fullPath: '/d/$designId'
      preLoaderRoute: typeof DDesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$designId/': {
      id: '/d/$designId/'
      path: '/'
      fullPath: '/d/$designId/'
      preLoaderRoute: typeof DDesignIdIndexRouteImport
      parentRoute: typeof DDesignIdRoute
    }
  }
}

interface DDesignIdRouteChildren {
  DDesignIdIndexRoute: typeof DDesignIdIndexRoute
}

const DDesignIdRouteChildren: DDesignIdRouteChildren = {
  DDesignIdIndexRoute: DDesignIdIndexRoute,
}

const DDesignIdRouteWithChildren = DDesignIdRoute._addFileChildren(
  DDesignIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DDesignIdRoute: DDesignIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
